/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/**/*.html", "./public/**/*.js", "./src/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#001c37",
        "on-primary-fixed-variant": "#574500",
        "on-tertiary-container": "#294b42",
        "tertiary": "#b1d6ca",
        "surface-bright": "#383a36",
        "error": "#ffb4ab",
        "on-surface-variant": "#d0c5af",
        "outline-variant": "#4d4635",
        "on-primary": "#3c2f00",
        "background": "#121411",
        "error-container": "#93000a",
        "tertiary-fixed": "#c5eadf",
        "on-secondary-fixed-variant": "#07497d",
        "surface-container-highest": "#333532",
        "tertiary-fixed-dim": "#aacec3",
        "tertiary-container": "#96baaf",
        "secondary-fixed": "#d2e4ff",
        "surface-container": "#1e201d",
        "primary-fixed-dim": "#e9c349",
        "on-secondary": "#00325a",
        "surface-tint": "#e9c349",
        "on-background": "#e3e3de",
        "secondary": "#a0c9ff",
        "on-primary-fixed": "#241a00",
        "on-primary-container": "#554300",
        "inverse-primary": "#735c00",
        "surface-variant": "#333532",
        "inverse-surface": "#e3e3de",
        "secondary-container": "#0d4b80",
        "primary-container": "#d4af37",
        "outline": "#99907c",
        "surface-container-low": "#1a1c19",
        "surface-dim": "#121411",
        "inverse-on-surface": "#2f312e",
        "on-secondary-container": "#8cbbf7",
        "primary-fixed": "#ffe088",
        "surface": "#121411",
        "on-tertiary": "#14362e",
        "secondary-fixed-dim": "#a0c9ff",
        "primary": "#f2ca50",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#2b4d44",
        "on-tertiary-fixed": "#00201a",
        "on-error-container": "#ffdad6",
        "on-surface": "#e3e3de",
        "surface-container-high": "#292a27",
        "surface-container-lowest": "#0d0f0c",
        neon: {
          cyan: "#00f5ff",
          pink: "#ff0080",
          gold: "#ffd700",
          green: "#39ff14",
          purple: "#bf00ff",
        },
      },
      fontFamily: {
        display: ["EB Garamond", "serif"],
        body: ["Inter", "sans-serif"],
      },
      keyframes: {
        slideUp: {
          "0%": { opacity: 0, transform: "translateY(16px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        shake: {
          "0%,100%": { transform: "translateX(0)" },
          "25%": { transform: "translateX(-6px)" },
          "75%": { transform: "translateX(6px)" },
        },
        popIn: {
          "0%": { opacity: 0, transform: "scale(0.85)" },
          "100%": { opacity: 1, transform: "scale(1)" },
        },
      },
      animation: {
        "slide-up": "slideUp 0.35s ease-out forwards",
        shake: "shake 0.4s ease",
        "pop-in": "popIn 0.25s ease-out forwards",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
